"""Path resolution for the compass rule table (D-2026-62).

Compass state lives at ``<state-dir>/compass/`` where ``<state-dir>`` is
the per-target directory resolved by the centralized state registry
(``<apiary>/.repos/<name>-<id>/``). The launcher exports
``APIARY_TARGET_STATE_DIR`` after registry lookup so this module can
return the correct path without re-running the resolver. When that env
var is unset (direct invocation, tests, or unmigrated targets), we fall
back to the legacy in-repo path ``<git-repo-root>/.apiary/compass/``.

Layout under ``<state-dir>/compass/``::

    turns/<sid>.jsonl              (assistant_text, user_turn, ts) pairs, appended
                                   by the Stop hook core/hooks/compass_pair_log.py
    turns/<sid>.cursor.json        byte offset + carried assistant text, so the
                                   hook reads only what the last turn appended
    events/<sid>.json              Sonnet-classified events (compass/classify.py)
    events/<sid>.heuristics.jsonl  Stop-hook output heuristics (compass/heuristics.py)
    rules.md                       the second-person rule table, regenerated by
                                   compass/rules.py build from seed + manual + events
    rules_manual.json              hand-added / accepted rows (same row schema as
                                   compass/seed_rules.json); optional
    observations/                  read-only history of the retired observation
                                   pipeline (nothing writes here since D-2026-62)

The seed table ships with the module at ``compass/seed_rules.json``.
"""

from __future__ import annotations

import json
from pathlib import Path

# Path resolution and the two names that describe it live in core.utils.state -
# re-exported here so callers (and tests) can keep saying ``store.<NAME>``
# while there is exactly one definition in the tree (review X-3).
from core.utils.state import (  # noqa: F401
    LEGACY_STATE_DIRNAME as APIARY_STATE_DIRNAME,
)
from core.utils.state import (
    TARGET_STATE_DIR_ENV,  # noqa: F401 — re-export: the compass tests read it
    # as compass.store.TARGET_STATE_DIR_ENV.
    resolve_state_dir,
)

COMPASS_SUBDIR = "compass"


def compass_dir(start: Path | None = None) -> Path:
    """Return the compass state directory.

    Delegates to :func:`core.utils.state.resolve_state_dir`, which is the
    one place the precedence lives (launcher env var → the repo's pins →
    the legacy ``.apiary/pointer`` breadcrumb → ``<repo>/.apiary/`` →
    ``<cwd>/.apiary/`` outside a git repo). See its docstring.
    """
    return resolve_state_dir(start, subdir=COMPASS_SUBDIR, cwd_fallback=True)


# ---------------------------------------------------------------------------
# Rule-table pipeline: turn pairs -> classified events -> rules.md
# ---------------------------------------------------------------------------

TURNS_DIRNAME = "turns"
EVENTS_DIRNAME = "events"
RULES_FILENAME = "rules.md"
MANUAL_RULES_FILENAME = "rules_manual.json"
#: ``events/<sid>.heuristics.jsonl`` — the Stop-hook output heuristics
#: (``compass/heuristics.py``); a suffix ``load_events``'s ``*.json`` never matches.
HEURISTICS_SUFFIX = ".heuristics.jsonl"
SEED_RULES_FILE = Path(__file__).resolve().parent / "seed_rules.json"


def short_session_id(session_id: str) -> str:
    """8-char lowercase prefix — the filename stem every compass file uses."""
    return session_id.split("-", 1)[0][:8].lower()


def turns_dir(start: Path | None = None) -> Path:
    return compass_dir(start) / TURNS_DIRNAME


def events_dir(start: Path | None = None) -> Path:
    return compass_dir(start) / EVENTS_DIRNAME


def turns_path(session_id: str, start: Path | None = None) -> Path:
    return turns_dir(start) / f"{short_session_id(session_id)}.jsonl"


def cursor_path(session_id: str, start: Path | None = None) -> Path:
    return turns_dir(start) / f"{short_session_id(session_id)}.cursor.json"


def events_path(session_id: str, start: Path | None = None) -> Path:
    return events_dir(start) / f"{short_session_id(session_id)}.json"


def heuristics_path(session_id: str, start: Path | None = None) -> Path:
    return events_dir(start) / f"{short_session_id(session_id)}{HEURISTICS_SUFFIX}"


def rules_path(start: Path | None = None) -> Path:
    return compass_dir(start) / RULES_FILENAME


def manual_rules_path(start: Path | None = None) -> Path:
    return compass_dir(start) / MANUAL_RULES_FILENAME


def load_seed_rules() -> dict:
    """The shipped seed table (``compass/seed_rules.json``) as a dict."""
    return json.loads(SEED_RULES_FILE.read_text(encoding="utf-8"))
