#!/usr/bin/env python3
"""Scribe — structured note management for LLM session continuity.

This module is the command line: argparse, one ``cmd_*`` handler per verb,
and the printing. Everything a handler does beyond that lives next door —

===================  =======================================================
``scribe.store``     the storage engine: folders, indexes, bodies, counters
``scribe.policy``    what auto-archives and when
``scribe.maintenance`` repair, backfill, backup/restore, retrotag
``scribe.templates`` per-type templates and the required-section gate
``scribe.infer``     tag/area inference (off unless asked)
``scribe.formatting`` display IDs, ages, colour, list rendering
``scribe.paths``     where the state dir is, and who is writing
``scribe.cli_args``  the argparse declaration — the CLI contract, in one place
===================  =======================================================

Notes are operational state — deferred work, handoffs, decisions — stored one
folder per type (``todos/``, ``handoffs/``, ``decisions/``, ...) as
``<state-dir>/scribe/<folder>/<year>/<seq>.md`` with an ``index.jsonl`` beside
them. Learnings are the same shape under ``learnings/`` and never auto-archive.

Requires PYTHONUTF8=1 on Windows. Run ``notes.py --help`` for the verbs — the
usage block that used to live here is generated by argparse, and a copy of it
in a docstring is a copy that goes stale.
"""

import sys
from datetime import datetime, timezone
from pathlib import Path

# Repo root on sys.path so `core.*` resolves however this file was invoked.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from core.session import SessionId
from scribe import formatting, infer, maintenance, paths, policy, templates
from scribe.cli_args import (
    build_parser,
    check_length,
    content_from_args,
    die,
    tag_list,
)
from scribe.formatting import format_id as _format_id
from scribe.store import BRIEF_SUMMARY_MAX, ScribeStore, derive_summary
from scribe.templates import (
    template_path,
)

MAX_CONTENT_LENGTH = 100_000  # bytes; prevents runaway JSONL file growth
MAX_SUMMARY_LENGTH = 300  # chars; keeps index.jsonl lines small and startup injection cheap
MAX_LAST = 10_000  # upper bound for --last to prevent misleading output

#: Report lines printed in full before a maintenance command truncates.
_REPORT_LINE_CAP = 50

#: Commands that inherit role/mission from the session identity. Read
#: commands must not: an absent --role means "no filter" there, so inheriting
#: one would hide every note written before identities existed.
_WRITE_COMMANDS = frozenset({"add", "learn", "update"})


# --------------------------------------------------------------------------- #
# Shared helpers
# --------------------------------------------------------------------------- #


def _print_capped(lines: list) -> None:
    """Print at most ``_REPORT_LINE_CAP`` report lines, then a count of the rest.

    A repair over a four-year corpus can name thousands of entries; the cap
    keeps a terminal (and a hook's captured output) readable while still
    saying how much was elided.
    """
    for line in lines[:_REPORT_LINE_CAP]:
        print(line)
    if len(lines) > _REPORT_LINE_CAP:
        print(f"  ... and {len(lines) - _REPORT_LINE_CAP} more")


def _by_role_mission(args, rows: list) -> list:
    """Keep only rows matching ``--role``/``--mission`` when either is given.

    Case-insensitive, and an unset filter matches everything — including rows
    written before roles existed, which carry neither field.
    """
    for field in ("role", "mission"):
        wanted = getattr(args, field, None)
        if wanted:
            rows = [r for r in rows if r.get(field, "").lower() == wanted.lower()]
    return rows


def _parse_id_arg(raw: str, store=None) -> tuple:
    """Parse a ``TYPE-YEAR-seq`` ID argument; exit 1 on anything else."""
    parsed = formatting.parse_id(raw)
    if parsed is None:
        die(f"invalid ID: {raw.strip()}")
    return parsed


def _note_id_arg(args, *, reject: str) -> tuple:
    """Parse a note ID, rejecting learning IDs with a verb-specific message."""
    note_type, year, seq = _parse_id_arg(str(args.id))
    if note_type == "learning":
        die(f"{args.id} is a learning{reject}.")
    return note_type, year, seq


def _learning_id_arg(args) -> tuple:
    """Parse a learning ID, rejecting note IDs."""
    note_type, year, seq = _parse_id_arg(str(args.id))
    if note_type != "learning":
        die(f"{args.id} is a {note_type}, not a learning.")
    return note_type, year, seq


def _require_updated(updated, display_id: str):
    """Exit 1 when ``store.update_note`` reported that nothing was written.

    ``update_note`` is archive-aware, so ``None`` here means the note really
    is gone (deleted, or moved between the read and the write) — printing
    "Marked X as done." in that case is the failure fixed in Phase 1.5.
    """
    if updated is None:
        die(
            f"note {display_id} could not be updated — no matching index entry "
            "in the active or archive index. Run `notes.py repair`."
        )
    return updated


# --------------------------------------------------------------------------- #
# Notes
# --------------------------------------------------------------------------- #


def cmd_add(args):
    store = args.store

    # Idempotency guard for /wrapup: skip when this session already has a
    # handoff. Searches archived too, because "keep only the latest handoff"
    # moves the previous one to the archive almost immediately.
    if getattr(args, "if_no_handoff_for", None):
        try:
            target_sid = SessionId(args.if_no_handoff_for)
        except ValueError as e:
            print(f"Error: {e}", file=sys.stderr)
            return
        for handoff in store.list_notes(note_type="handoff", status="all"):
            if target_sid.matches(handoff.get("session", "")):
                print(
                    f"Handoff for session {target_sid.short} already exists "
                    f"({handoff.get('display_id', _format_id(handoff))}). Skipping."
                )
                return

    content = check_length(content_from_args(args), MAX_CONTENT_LENGTH, "content", unit="bytes")

    summary = (getattr(args, "summary", "") or "").strip()
    if args.type == "handoff" and not summary:
        die(
            "--summary is required for --type handoff. Provide a one-line "
            'abstract (e.g. "Session abc12345: fixed X, decided Y").'
        )
    check_length(summary, MAX_SUMMARY_LENGTH, "--summary")
    brief_summary = (getattr(args, "brief_summary", "") or "").strip()
    check_length(brief_summary, BRIEF_SUMMARY_MAX, "--brief-summary")

    # Template gate: one check, one attempt, --force to bypass. Forward-only —
    # it runs on `add`, never against notes already written.
    message, fatal = templates.gate(
        store.state_dir, args.type, content, force=getattr(args, "force", False)
    )
    if message:
        print(message, file=sys.stderr)
    if fatal:
        sys.exit(1)

    # --unique-tag skips the add (exit 0) when an active note already carries
    # the tag; otherwise the tag is added to this note (spec §5.14).
    tags = tag_list(args)
    unique_tag = (getattr(args, "unique_tag", "") or "").strip()
    if unique_tag:
        existing = store.find_active_with_tag(unique_tag)
        if existing is not None:
            brief = existing.get("brief_summary") or existing.get("summary") or ""
            print(
                f"skipped (active {_format_id(existing)} already carries tag "
                f"'{unique_tag}'): {brief}"
            )
            return
        if unique_tag not in tags:
            tags.append(unique_tag)

    metadata = {}
    if getattr(args, "auto", False):
        metadata["auto_generated"] = True
    if getattr(args, "role", ""):
        metadata["role"] = args.role
    if getattr(args, "mission", ""):
        metadata["mission"] = args.mission
    if tags:
        metadata["tags"] = tags

    entry = store.add_note(
        note_type=args.type,
        content=content,
        session_id=args.session_id or "",
        summary=summary,
        brief_summary=brief_summary,
        **metadata,
    )
    print(f"Added {_format_id(entry)} ({entry['type']})")
    policy.run_auto_archive(store)


def cmd_list(args):
    store = args.store
    if args.archive:
        status, source = "archived", "archive"
    else:
        status, source = ("all" if args.all else "active"), "active"

    # `list` is a read command and does not mutate state. The retention sweep
    # runs from `add`, from session startup, and on demand via `tidy` —
    # listing notes must not make them disappear (Phase 1.5).
    notes_list = store.list_notes(note_type=args.type or None, status=status, search=args.search)

    if getattr(args, "deferred", False):
        notes_list = [n for n in notes_list if n.get("status") == "deferred"]
    elif not args.all and not args.archive:
        notes_list = [
            n for n in notes_list if n.get("status") not in ("done", "dropped", "deferred")
        ]

    if args.session:
        try:
            sid = SessionId(args.session)
        except ValueError as e:
            print(f"Error: {e}", file=sys.stderr)
            return
        notes_list = [n for n in notes_list if sid.matches(n.get("session", ""))]
    notes_list = _by_role_mission(args, notes_list)

    if args.last is not None:
        if args.last <= 0:
            die("--last must be a positive integer")
        notes_list = notes_list[-min(args.last, MAX_LAST) :]

    if not notes_list:
        print(f"No {source} notes found.")
        return
    for entry in notes_list:
        print(formatting.note_line(entry))


def cmd_get(args):
    store = args.store
    note_type, year, seq = _parse_id_arg(args.id)
    is_learning = note_type == "learning"

    if is_learning:
        note = store.get_learning(year, seq)
    else:
        note = store.get_note(note_type, year, seq)
        if note and note.get("_from_archive"):
            print("[from archive]")

    if not note:
        print(f"Note {args.id} not found.", file=sys.stderr)
        sys.exit(1)

    for line in formatting.note_detail(note, is_learning=is_learning):
        print(line)


def _transition(
    args, *, target: str, already: str, blocked_from: tuple = (), blocked_message: str = ""
):
    """Move a note to *target* status, or explain why it cannot move.

    The status verbs (done/drop/defer) differ only in the status they set,
    what they call it, and which prior statuses refuse the move — they were
    three near-identical twenty-line handlers. Returns the updated entry, or
    None when the note was already there.
    """
    store = args.store
    note_type, year, seq = _note_id_arg(args, reject=' — use "unlearn" to remove it')
    note = store.get_note(note_type, year, seq)
    if not note:
        print(f"Note {args.id} not found.", file=sys.stderr)
        sys.exit(1)
    status = note.get("status")
    if status == target:
        print(f"Note {args.id} is already {already}.")
        return None
    if status in blocked_from:
        die(blocked_message.format(id=args.id, status=status))
    return _require_updated(store.update_note(note_type, year, seq, status=target), args.id)


def cmd_done(args):
    updated = _transition(args, target="done", already="marked done")
    if updated is None:
        return
    # External-ticket close signal (spec §5.14 / A2). Non-destructive:
    # surfaces the link for the Asana tool to observe; closes nothing local.
    if updated.get("type") == "todo":
        links = policy.external_ticket_links(updated)
        if links:
            print(
                f"[external ticket link(s) {', '.join(links)}: close observed by the Asana tool]",
                file=sys.stderr,
            )
    print(f"Marked {args.id} as done.")


def cmd_drop(args):
    if (
        _transition(
            args,
            target="dropped",
            already="dropped",
            blocked_from=("done",),
            blocked_message="note {id} is already done; cannot drop.",
        )
        is not None
    ):
        print(f"Marked {args.id} as dropped.")


def cmd_defer(args):
    updated = _transition(
        args,
        target="deferred",
        already="deferred",
        blocked_from=("done", "dropped"),
        blocked_message="note {id} is {status}; cannot defer a closed note.",
    )
    if updated is None:
        return
    where = " (it stays in the archive)" if updated.get("_from_archive") else ""
    print(f'Deferred {args.id}{where}. Use "resume {args.id}" to bring it back.')


def cmd_resume(args):
    store = args.store
    note_type, year, seq = _note_id_arg(args, reject=" and cannot be resumed")
    note = store.get_note(note_type, year, seq)
    if not note:
        print(f"Note {args.id} not found.", file=sys.stderr)
        sys.exit(1)
    if note.get("status") != "deferred":
        print(f"Note {args.id} is not deferred (status: {note.get('status', '?')}).")
        return
    updated = _require_updated(store.update_note(note_type, year, seq, status="active"), args.id)
    if updated.get("_from_archive"):
        # An archived note that becomes active again has to leave the archive,
        # or `list` and the startup banner never show it.
        store.unarchive_note(note_type, year, seq)
        print(f"Resumed {args.id} (moved back out of the archive).")
        return
    print(f"Resumed {args.id}.")


def cmd_unarchive(args):
    note_type, year, seq = _note_id_arg(args, reject=" and does not use archive")
    entry = args.store.unarchive_note(note_type, year, seq)
    if entry is None:
        print(f"Note {args.id} not found in archive.", file=sys.stderr)
        sys.exit(1)
    print(f"Unarchived {args.id} (status preserved: {entry.get('status', '?')}).")


def cmd_update(args):
    if getattr(args, "content_file", None) is not None:
        args.content = content_from_args(args)
    brief_override = (getattr(args, "brief_summary", "") or "").strip()
    add_tags = [t for t in (getattr(args, "add_tag", None) or []) if t]
    remove_tags = [t for t in (getattr(args, "remove_tag", None) or []) if t]
    if (
        args.content is None
        and args.session_id is None
        and not brief_override
        and not add_tags
        and not remove_tags
    ):
        die("provide --content, --session-id, --brief-summary, --add-tag, and/or --remove-tag")
    if args.content is not None:
        check_length(args.content, MAX_CONTENT_LENGTH, "content", unit="bytes")
    check_length(brief_override, BRIEF_SUMMARY_MAX, "--brief-summary")

    store = args.store
    note_type, year, seq = _note_id_arg(args, reject=' — use "unlearn" to remove it')
    note = store.get_note(note_type, year, seq)
    if not note:
        print(f"Note {args.id} not found.", file=sys.stderr)
        sys.exit(1)
    # A done note's content is frozen, but tag/brief/session mutation stays
    # allowed — the Asana tool flips status tags on closed mirrors (spec §5.14).
    if note.get("status") == "done" and args.content is not None:
        die(f"note {args.id} is already done; cannot edit content.")

    kwargs = {}
    if args.content is not None:
        kwargs["content"] = args.content
        kwargs["summary"] = derive_summary(args.content)
    if args.session_id is not None:
        kwargs["session"] = args.session_id
    if brief_override:
        kwargs["brief_summary"] = brief_override
    if add_tags:
        kwargs["add_tags"] = add_tags
    if remove_tags:
        kwargs["remove_tags"] = remove_tags
    _require_updated(store.update_note(note_type, year, seq, **kwargs), args.id)
    print(f"Updated {args.id}.")


def cmd_archive(args):
    store = args.store
    if args.before:
        try:
            cutoff = datetime.strptime(args.before, "%Y-%m-%d").replace(tzinfo=timezone.utc)
        except ValueError:
            die(f"--before must be in YYYY-MM-DD format, got {args.before!r}")
    else:
        cutoff = policy.default_archive_cutoff()

    keys = policy.select_archivable_before(store.list_notes(status="active"), cutoff)
    for note_type, year, seq in keys:
        store.archive_note(note_type, year, seq)
    if not keys:
        print("Nothing to archive.")
        return
    print(f"Archived {len(keys)} notes (before {cutoff.strftime('%Y-%m-%d')}).")


def cmd_tidy(args):
    """Run the retention sweep explicitly.

    The same policy `add` and session startup apply, exposed as a verb so a
    read command (`list`) never has to mutate state to keep the active view
    tidy. Safe to run any time; prints what it moved.
    """
    archived = policy.run_auto_archive(args.store)
    print(f"Tidied {archived} notes into the archive." if archived else "Nothing to tidy.")


# --------------------------------------------------------------------------- #
# Learnings
# --------------------------------------------------------------------------- #


def cmd_learn(args):
    store = args.store
    content = check_length(content_from_args(args), MAX_CONTENT_LENGTH, "content", unit="bytes")
    brief_summary = (getattr(args, "brief_summary", "") or "").strip()
    check_length(brief_summary, BRIEF_SUMMARY_MAX, "--brief-summary")

    metadata = {}
    if getattr(args, "role", ""):
        metadata["role"] = args.role
    if getattr(args, "mission", ""):
        metadata["mission"] = args.mission

    tags = tag_list(args)
    areas = [a for a in (getattr(args, "area", None) or []) if a]
    tags, areas = infer.resolve(args, content, store, tags, areas)

    entry = store.add_learning(
        content=content,
        session_id=args.session_id or "",
        brief_summary=brief_summary,
        tags=tags,
        areas=areas,
        supersedes=(getattr(args, "supersedes", "") or "").strip() or None,
        **metadata,
    )
    print(f"Learned {_format_id(entry)}")


def cmd_learnings(args):
    store = args.store
    learnings = store.list_learnings(
        search=args.search, tag=getattr(args, "tag", None), area=getattr(args, "area", None)
    )
    learnings = _by_role_mission(args, learnings)

    if not learnings:
        print("No learnings found.")
        return
    if getattr(args, "index", False):
        for line in formatting.learnings_index(learnings):
            print(line)
        return
    for entry in learnings:
        if args.full:
            full = store.get_learning(entry["year"], entry["seq"])
            content = full.get("content", "") if full else entry.get("summary", "")
            print(f"{_format_id(entry)}: {content}")
        else:
            print(formatting.learning_line(entry))


def cmd_unlearn(args):
    _, year, seq = _learning_id_arg(args)
    if args.store.remove_learning(year, seq) is None:
        print(f"Learning {args.id} not found.", file=sys.stderr)
        sys.exit(1)
    print(f"Removed learning {args.id}.")


def cmd_archive_learning(args):
    """Archive a learning by ID. Parallels note archival but for the L- prefix.

    Exists so `/review-learnings` and hand-run cleanup can retire a stale
    learning without writing a replacement (which is what `supersede` is for).
    """
    _, year, seq = _learning_id_arg(args)
    if args.store.archive_learning(year, seq) is None:
        print(f"Learning {args.id} not found or already archived.", file=sys.stderr)
        sys.exit(1)
    print(f"Archived learning {args.id}.")


def cmd_supersede(args):
    """Archive an old learning and write a replacement pointing back at it.

    Frontmatter on the new learning carries ``supersedes: L-old`` so the
    lineage is visible when reading the .md.
    """
    if getattr(args, "content_file", None) is not None:
        args.content = content_from_args(args)
    store = args.store
    _, year, seq = _learning_id_arg(args)

    existing = store.get_learning(year, seq)
    if existing is None:
        print(f"Learning {args.id} not found.", file=sys.stderr)
        sys.exit(1)
    if existing.get("_from_archive"):
        die(f"{args.id} is already archived — cannot supersede.")

    content = check_length(args.content, MAX_CONTENT_LENGTH, "content", unit="bytes")
    tags = tag_list(args)
    areas = [a for a in (getattr(args, "area", None) or []) if a]
    tags, areas = infer.resolve(args, content, store, tags, areas)

    old_display_id = _format_id(existing)
    if store.archive_learning(year, seq) is None:
        die(f"failed to archive {args.id}.")

    metadata = {}
    if getattr(args, "role", ""):
        metadata["role"] = args.role
    if getattr(args, "mission", ""):
        metadata["mission"] = args.mission
    new_entry = store.add_learning(
        content=content,
        session_id=args.session_id or "",
        tags=tags,
        areas=areas,
        supersedes=old_display_id,
        **metadata,
    )
    print(f"Superseded {old_display_id} with {_format_id(new_entry)}")


# --------------------------------------------------------------------------- #
# Maintenance — the work is in scribe/maintenance.py
# --------------------------------------------------------------------------- #


def cmd_mark_reviewed(args):
    """Stamp the learnings review marker the startup banner reads.

    Exists so `/review-learnings` can call a verb through the launcher
    instead of a `python -c` one-liner that resolved the wrong state dir.
    """
    try:
        marker = maintenance.mark_reviewed(args.store)
    except OSError as e:
        die(f"could not stamp the learnings review marker: {e}")
    print(f"Stamped learnings review: {marker}")


def cmd_repair(args):
    """Reconcile every index against the .md bodies beside it."""
    dry_run = bool(getattr(args, "dry_run", False))
    report = maintenance.repair(args.store, dry_run=dry_run)
    if not report.found_data:
        print("No scribe data found")
        return 0
    for warning in report.warnings:
        print(warning, file=sys.stderr)
    print(report.summary(dry_run))
    for line in report.lines:
        print(line)


def cmd_backfill_brief(args):
    """Populate brief_summary on every entry that lacks one."""
    dry_run = bool(getattr(args, "dry_run", False))
    report = maintenance.backfill_brief(
        args.store, dry_run=dry_run, force=bool(getattr(args, "force", False))
    )
    print(report.summary(dry_run))
    _print_capped(report.lines)


def cmd_retrotag(args):
    """Infer tags and areas for every learning that has neither.

    The one scribe command whose whole point is a model call, so it ignores
    the `--infer` switch the write commands consult. Skips anything already
    tagged, which makes a half-finished run cheap to resume.
    """
    dry_run = bool(getattr(args, "dry_run", False))
    report = maintenance.retrotag(
        args.store,
        dry_run=dry_run,
        model=getattr(args, "model", None),
        limit=getattr(args, "limit", None),
    )
    print(report.summary(dry_run))
    _print_capped(report.lines)
    for err in report.errors[:20]:
        print(f"  - {err}", file=sys.stderr)
    if len(report.errors) > 20:
        print(f"  ... and {len(report.errors) - 20} more", file=sys.stderr)


def cmd_backup(args):
    """Snapshot every index.jsonl into ``<state-dir>/backups/<date>/``."""
    state_dir = args.store.state_dir
    root = maintenance.backups_root(state_dir)
    root.mkdir(parents=True, exist_ok=True)
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    target, count = maintenance.create_backup(state_dir, root, date_str)
    print(f"Backup created: {target} ({count} files)")
    pruned = maintenance.prune_backups(root, args.retain)
    if pruned:
        print(f"Pruned {len(pruned)} old backup(s)")


def cmd_restore(args):
    """Copy the indexes from a dated snapshot back over the live ones."""
    state_dir = args.store.state_dir
    if getattr(args, "list", False):
        snapshots = maintenance.list_backups(state_dir)
        if not snapshots:
            print(f"No snapshots under {maintenance.backups_root(state_dir)}.")
            return
        for snapshot in snapshots:
            print(snapshot.name)
        return
    dry_run = bool(getattr(args, "dry_run", False))
    try:
        report = maintenance.restore_backup(
            state_dir, getattr(args, "source", None), dry_run=dry_run
        )
    except FileNotFoundError as e:
        die(str(e))
    print(report.summary(dry_run))
    _print_capped(report.lines)
    if report.restored and not dry_run:
        print(
            "Run `notes.py repair` next: any body written after the snapshot "
            "has no index row until it is rebuilt."
        )


def cmd_template(args):
    """Inspect the per-type templates that gate `add`."""
    state_dir = args.store.state_dir
    action = getattr(args, "template_action", None)
    if action is None:
        die("subcommand required (show | path | list)")

    if action == "list":
        for line in templates.overview(state_dir):
            print(line)
        return

    note_type = args.type
    if action == "path":
        print(template_path(state_dir, note_type))
        return

    rendered = templates.render(state_dir, note_type)
    if rendered is None:
        print(
            f"(no template for type {note_type!r}; create "
            f"{template_path(state_dir, note_type)} to add one)",
            file=sys.stderr,
        )
        sys.exit(1)
    print(rendered, end="")


COMMANDS = {
    "add": cmd_add,
    "list": cmd_list,
    "get": cmd_get,
    "show": cmd_get,
    "done": cmd_done,
    "drop": cmd_drop,
    "defer": cmd_defer,
    "resume": cmd_resume,
    "unarchive": cmd_unarchive,
    "update": cmd_update,
    "archive": cmd_archive,
    "tidy": cmd_tidy,
    "mark-reviewed": cmd_mark_reviewed,
    "learn": cmd_learn,
    "learnings": cmd_learnings,
    "unlearn": cmd_unlearn,
    "archive-learning": cmd_archive_learning,
    "supersede": cmd_supersede,
    "repair": cmd_repair,
    "backfill-brief": cmd_backfill_brief,
    "retrotag": cmd_retrotag,
    "backup": cmd_backup,
    "restore": cmd_restore,
    "template": cmd_template,
}


def _apply_session_identity(args) -> None:
    """Fill role/mission/session-id from the session identity where blank.

    Only write commands inherit role/mission — for a read command an absent
    --role means "no filter", and inheriting one would hide every note
    written before identities existed. The session id is filled for handoffs
    regardless, so a hand-written handoff is still attributable.
    """
    default_role, default_mission, default_sid = paths.session_identity()
    if args.command in _WRITE_COMMANDS:
        if hasattr(args, "role") and not getattr(args, "role", ""):
            args.role = default_role
        if hasattr(args, "mission") and not getattr(args, "mission", ""):
            args.mission = default_mission
    if (
        hasattr(args, "session_id")
        and not getattr(args, "session_id", "")
        and getattr(args, "type", "") == "handoff"
    ):
        args.session_id = default_sid


def main():
    parser = build_parser()
    args = parser.parse_args()
    if not args.command:
        parser.print_help()
        return

    # Identity is read only once a command is present, so `--help` works
    # without a valid session identity file.
    _apply_session_identity(args)

    try:
        state_dir = paths.resolve_store_dir(args.project)
    except paths.ProjectKeyError as e:
        die(str(e))
    args.store = ScribeStore(state_dir)

    handler = COMMANDS.get(args.command)
    if handler:
        try:
            handler(args)
        except TimeoutError as e:
            # FileLock gave up: another apiary process (a hook, a second
            # session) is holding an index lock. A traceback here is not an
            # answer; say what to do. `add` writes the body before the row, so
            # a body without a row may be left behind — `repair` reattaches it.
            die(
                f"index busy — could not acquire a scribe lock ({e}). "
                "Retry in a moment; if this was `add`, run `notes.py repair` to "
                "reattach any body written before the lock timed out."
            )
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
