"""Template for the per-repo apiary launcher.

The launcher is a tiny shim copied into ``<repo>/.claude/apiary/launch.py``
by ``apiary install --target <repo>``. It reads the repo's
``main-apiary-pointer.json`` to find main-apiary, then dispatches to the
named script under main-apiary with the caller's cwd intact. See
``docs/architecture/per-repo-install.md`` for the full contract.

This template is rendered to a file rather than imported because each
bootstrapped repo carries its own copy under ``.claude/apiary/``. The
rendered file has no dependency on apiary being importable — it only
needs Python's stdlib.
"""
from __future__ import annotations

# The literal text written to <repo>/.claude/apiary/launch.py. Edit here
# to change every future install; existing installs pick up edits on the
# next ``apiary install`` (which is idempotent).
LAUNCHER_PY = '''#!/usr/bin/env python3
"""Apiary per-repo launcher. Generated by `apiary install`. Do not edit.

Reads <repo>/.claude/apiary/{main-apiary-pointer,self-pointer}.json to find
main-apiary and the per-target state directory, then dispatches to a script
inside main-apiary. Exits 0 (silently) when main-apiary is unreachable so
a missing checkout never blocks Claude Code session startup.

Env vars set for the dispatched script:
- APIARY_MAIN_REPO        — main-apiary's absolute path
- APIARY_TARGET_STATE_DIR — <main-apiary>/.repos/<name>-<uid>/, the
  per-target state dir scribe / runner / compass / etc. read.
"""
import json
import os
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
MAIN_POINTER = HERE / "main-apiary-pointer.json"
SELF_POINTER = HERE / "self-pointer.json"


def _read_json(p: Path) -> dict | None:
    if not p.is_file():
        return None
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return data if isinstance(data, dict) else None


def _resolve_main_apiary() -> Path | None:
    data = _read_json(MAIN_POINTER)
    if data is None:
        return None
    path = data.get("main_apiary_path", "")
    if not path:
        return None
    return Path(path)


def _resolve_state_dir(main_apiary: Path) -> Path | None:
    """Return <main-apiary>/.repos/<name>-<uid>/ from self-pointer."""
    data = _read_json(SELF_POINTER)
    if data is None:
        return None
    name = data.get("name") or ""
    uid = data.get("uid")
    if not name or uid is None:
        return None
    candidate = main_apiary / ".repos" / f"{name}-{uid}"
    return candidate if candidate.is_dir() else None


def main() -> int:
    main_apiary = _resolve_main_apiary()
    if main_apiary is None or not main_apiary.is_dir():
        # Loud-warn-and-skip. Hooks must always exit 0 — a non-zero exit
        # here would block tool calls.
        print(
            f"[apiary] main-apiary not reachable via {MAIN_POINTER}; "
            "running as vanilla Claude session.",
            file=sys.stderr,
        )
        return 0

    # `--print-repo-path` mode: bash skills shell out to discover the
    # apiary repo path (e.g. `apiary_root=$(... --print-repo-path)`).
    # Compatibility shim with the historical ~/.claude/apiary_launch.py.
    if len(sys.argv) >= 2 and sys.argv[1] == "--print-repo-path":
        print(main_apiary)
        return 0

    if len(sys.argv) < 2:
        print("[apiary] usage: launch.py <script-relative-to-main-apiary> [args...]",
              file=sys.stderr)
        return 2

    script = main_apiary / sys.argv[1]
    if not script.is_file():
        # A settings.json entry outlived the script it points at — normally
        # a hook apiary deleted, in a repo that has not been re-bootstrapped.
        # Say so once, on stderr, and exit 0: a non-zero exit or a traceback
        # here would surface as a hook error on every tool call.
        print(
            f"[apiary] hook script removed: {script} — re-run apiary install",
            file=sys.stderr,
        )
        return 0  # do not block

    env = os.environ.copy()
    env["APIARY_MAIN_REPO"] = str(main_apiary)
    state_dir = _resolve_state_dir(main_apiary)
    if state_dir is not None:
        env["APIARY_TARGET_STATE_DIR"] = str(state_dir)
    return subprocess.run(
        [sys.executable, str(script), *sys.argv[2:]],
        env=env,
    ).returncode


if __name__ == "__main__":
    raise SystemExit(main())
'''
