"""Template for the per-repo apiary launcher.

The launcher is a tiny shim copied into ``<repo>/.claude/apiary/launch.py``
by ``apiary install --target <repo>``. It reads the repo's
``main-apiary-pointer.json`` to find main-apiary, then dispatches to the
named script under main-apiary with the caller's cwd intact. See
MIGRATION-PLAN.md §7.7 for the full contract.

This template is rendered to a file rather than imported because each
bootstrapped repo carries its own copy under ``.claude/apiary/``. The
rendered file has no dependency on apiary being importable — it only
needs Python's stdlib.
"""
from __future__ import annotations

# The literal text written to <repo>/.claude/apiary/launch.py. Edit here
# to change every future install; existing installs pick up edits on the
# next ``apiary install`` (which is idempotent).
LAUNCHER_PY = '''#!/usr/bin/env python3
"""Apiary per-repo launcher. Generated by `apiary install`. Do not edit.

Reads <repo>/.claude/apiary/main-apiary-pointer.json to find main-apiary,
then dispatches to a script inside main-apiary with the caller's cwd
unchanged. Exits 0 (silently) when main-apiary is unreachable so a missing
checkout never blocks Claude Code session startup.
"""
import json
import os
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
POINTER = HERE / "main-apiary-pointer.json"


def _resolve_main_apiary() -> Path | None:
    if not POINTER.is_file():
        return None
    try:
        data = json.loads(POINTER.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    path = data.get("main_apiary_path", "") if isinstance(data, dict) else ""
    if not path:
        return None
    return Path(path)


def main() -> int:
    main_apiary = _resolve_main_apiary()
    if main_apiary is None or not main_apiary.is_dir():
        # Loud-warn-and-skip per MIGRATION-PLAN.md §7.1 / D32. Hooks must
        # always exit 0 — a non-zero exit here would block tool calls.
        print(
            f"[apiary] main-apiary not reachable via {POINTER}; "
            "running as vanilla Claude session.",
            file=sys.stderr,
        )
        return 0

    # `--print-repo-path` mode: bash skills shell out to discover the
    # apiary repo path (e.g. `apiary_root=$(... --print-repo-path)`).
    # Compatibility shim with the historical ~/.claude/apiary_launch.py.
    if len(sys.argv) >= 2 and sys.argv[1] == "--print-repo-path":
        print(main_apiary)
        return 0

    if len(sys.argv) < 2:
        print("[apiary] usage: launch.py <script-relative-to-main-apiary> [args...]",
              file=sys.stderr)
        return 2

    script = main_apiary / sys.argv[1]
    if not script.is_file():
        print(f"[apiary] script not found: {script}", file=sys.stderr)
        return 0  # do not block

    env = os.environ.copy()
    env["APIARY_MAIN_REPO"] = str(main_apiary)
    return subprocess.run(
        [sys.executable, str(script), *sys.argv[2:]],
        env=env,
    ).returncode


if __name__ == "__main__":
    raise SystemExit(main())
'''


def render() -> str:
    """Return the launcher source as a string. One-liner today; here so
    callers don't depend on the module-level constant name."""
    return LAUNCHER_PY
